layerrule = match:namespace logout_dialog, animation overshot 
layerrule = match:namespace logout_dialog, blur on
layerrule = match:namespace selection, animation blur
layerrule = match:namespace swaync-control-center, animation overshot
layerrule = match:namespace waybar, no_anim no
layerrule = match:namespace rofi, animation popin
layerrule = match:namespace launcher, animation slide top
# layerrule = blur, waybar
layerrule = match:namespace swww-daemon, animation fade
layerrule = match:namespace ^(notification|swaync-control-center)$, animation slide top
layerrule = match:namespace quickshell, animation fade 
# workspace = 2, rounding:false, shadow:false, gapsin:0, gapsout:0, border:false
